version: "3.8"
services:
  orion-ld:
    image: fiware/orion-ld
    hostname: orion-ld
    container_name: orion-ld
    environment:
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=orion
      - ORIONLD_TROE_HOST=timescale
    expose:
      - 1026
    ports:
      - 1026:1026
    depends_on:
      - mongo-db
      - timescale
    command: -dbhost mongo-db -logLevel ERROR -troePoolSize 10 -forwarding

  mongo-db:
    image: mongo:5.0
    hostname: mongo-db
    container_name: orion-ld-mongo-db
    networks:
      - default
    command: --nojournal
    volumes:
      - /data/docker/orion-ld/mongodb:/data

  # Other services
  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default
