version: "3.8"
services:
  orion-ld:
    image: fiware/orion-ld
    hostname: orion-ld
    container_name: orion-ld
    environment:
      - ORIONLD_TROE=TRUE
      - ORIONLD_TROE_USER=orion
      - ORIONLD_TROE_PWD=orion
      - ORIONLD_TROE_HOST=timescale
    expose:
      - 1026
    ports:
      - 1026:1026
    depends_on:
      - mongo-db
      - timescale
    command: -dbhost mongo-db -logLevel ERROR -troePoolSize 10 -forwarding

  mongo-db:
    image: mongo:5.0
    hostname: mongo-db
    container_name: orion-ld-mongo-db
    networks:
      - default
    command: --nojournal
    volumes:
      - /data/docker/orion-ld/mongodb:/data

  timescale:
    image: timescale/timescaledb-postgis:latest-pg12
    hostname: timescale
    container_name: timescale
    networks:
      - default
    ports:
      - 5432
    environment:
      POSTGRES_USER: orion
      POSTGRES_PASSWORD: orion
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: none
    volumes:
      - /data/docker/orion-ld/timeseries:/var/lib/postgresql/data

  mintaka:
    image: fiware/mintaka:latest
    hostname: mintaka
    container_name: mintaka
    environment:
      - DATASOURCES_DEFAULT_HOST=timescale
      - DATASOURCES_DEFAULT_USERNAME=orion
      - DATASOURCES_DEFAULT_PASSWORD=orion
      - DATASOURCES_DEFAULT_DATABSE=orion
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - default
